name: Release PA POS

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:renderer:prod && npx electron-builder --win --publish always

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build Linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:renderer:prod && npx electron-builder --linux --publish always
